"""add default srid to collection spatil extent

Revision ID: 75bf8e33702f
Revises: 85906f1e98e5
Create Date: 2026-05-26 22:52:05.726834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "75bf8e33702f"
down_revision: Union[str, Sequence[str], None] = "85906f1e98e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection",
        "spatial_extent",
        existing_type=Geometry(
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=Geometry(
            srid=4326,
            dimension=2,
            spatial_index=False,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection",
        "spatial_extent",
        existing_type=Geometry(
            srid=4326,
            dimension=2,
            spatial_index=False,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        type_=Geometry(
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
