"""make collection crs not null

Revision ID: b8ff6048e74f
Revises: 75bf8e33702f
Create Date: 2026-08-10 16:26:54.622877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8ff6048e74f"
down_revision: Union[str, Sequence[str], None] = "75bf8e33702f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CRS_84 = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        sa.text("UPDATE collection SET crs = :crs WHERE crs IS NULL").bindparams(
            sa.bindparam("crs", value=[CRS_84], type_=postgresql.JSONB)
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection",
        "crs",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collection",
        "crs",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
