from typing import Annotated

import alembic.command
import alembic.config
import alembic.util.exc
import cyclopts
from rich.table import Table

db_app = cyclopts.App(name="db")


@db_app.meta.default
def launcher(
        *tokens: Annotated[
            str,
            cyclopts.Parameter(show=False, allow_leading_hyphen=True)
        ],
):
    """Custom cli launcher that injects the alembic context if needed.

    This custom launcher detects if access to the alembic config is
    being requested by the underlying CLI command and injects it if needed.
    """
    command, bound, ignored = db_app.parse_args(tokens)
    additional_kwargs = {}
    if "alembic_config" in ignored:
        alembic_config = alembic.config.Config()
        alembic_config.set_main_option("script_location", "potto.db:migrations")
        alembic_config.set_main_option(
            "file_template",
            "%%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s",
        )

        additional_kwargs = {
            "alembic_config": alembic_config,
        }
    return command(*bound.args, **bound.kwargs, **additional_kwargs)


@db_app.command
def check_for_changes(
        *,
        alembic_config: Annotated[alembic.config.Config, cyclopts.Parameter(parse=False)],
):
    """Look for changes in the DB schema.

    This command checks if there are changes to the schema that warrant the
    generation of new migration files.
    """
    try:
        alembic.command.check(alembic_config)
    except alembic.util.exc.AutogenerateDiffsDetected as exc:
        db_app.console.print(exc)


@db_app.command
def generate_migration(
        migration_message: str,
        *,
        alembic_config: Annotated[alembic.config.Config, cyclopts.Parameter(parse=False)],
):
    """Generate migration files with any new database schema changes.

    Remember to inspect the autogenerated migration files in order to determine
    whether they correctly capture the changes in the code.
    """
    alembic.command.revision(
        alembic_config,
        message=migration_message,
        autogenerate=True,
    )


@db_app.command
def upgrade(
        *,
        alembic_config: Annotated[alembic.config.Config, cyclopts.Parameter(parse=False)],
        revision_identifier: str | None = None,
) -> None:
    """Apply any pending migration files."""
    db_app.console.print("Upgrading database...")
    revision_arg = "head" if revision_identifier is None else revision_identifier
    alembic.command.upgrade(alembic_config, revision_arg)
    db_app.console.print("Done!")


@db_app.command
def list_history(
        *,
        alembic_config: Annotated[alembic.config.Config, cyclopts.Parameter(parse=False)],
) -> None:
    """List database revision history"""
    alembic.command.history(alembic_config, indicate_current=True)


@db_app.command
def downgrade(
        revision_identifier: str,
        *,
        alembic_config: Annotated[alembic.config.Config, cyclopts.Parameter(parse=False)],
) -> None:
    """Downgrade the database to a previous revision."""
    db_app.console.print("Downgrading database...")
    alembic.command.downgrade(alembic_config, revision_identifier)
    db_app.console.print("Done!")
