import asyncio
import logging
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import alembic.command
import alembic.config
import alembic.util.exc
import cyclopts
import yaml

from ...exceptions import PottoException
from . import operations as postgis_operations
from .db.alembic_utils import build_alembic_config
from .db.queries import collections as collection_queries

if TYPE_CHECKING:
    from .manager import PostgisManager

logger = logging.getLogger(__name__)


def build_cli_group(manager: "PostgisManager") -> cyclopts.App:
    """Build the postgis manager's own CLI commands (``potto <group> ...``)."""
    app = cyclopts.App(name=manager.potto_cli_group)
    alembic_config = build_alembic_config(manager.config.database_dsn.unicode_string())

    @app.command
    def check_for_changes():
        """Look for changes in the DB schema.

        This command checks if there are changes to the schema that warrant the
        generation of new migration files.
        """
        try:
            alembic.command.check(alembic_config)
        except alembic.util.exc.AutogenerateDiffsDetected as exc:
            app.console.print(exc)

    @app.command(name="generate-migration")
    def generate_migration(migration_message: str):
        """Generate migration files with any new database schema changes.

        Remember to inspect the autogenerated migration files in order to determine
        whether they correctly capture the changes in the code.
        """
        alembic.command.revision(
            alembic_config,
            message=migration_message,
            autogenerate=True,
        )

    @app.command
    def upgrade(revision_identifier: str = "head") -> None:
        """Apply any pending migration files."""
        app.console.print("Upgrading database...")
        alembic.command.upgrade(alembic_config, revision_identifier)
        app.console.print("Done!")

    @app.command(name="list-history")
    def list_history() -> None:
        """List database revision history"""
        alembic.command.history(alembic_config, indicate_current=True)

    @app.command
    def downgrade(revision_identifier: str) -> None:
        """Downgrade the database to a previous revision."""
        app.console.print("Downgrading database...")
        alembic.command.downgrade(alembic_config, revision_identifier)
        app.console.print("Done!")

    @app.command(name="import-from-pygeoapi")
    async def import_from_pygeoapi(
        pygeoapi_configuration: Path,
        resource: list[str] | None = None,
        overwrite: bool = False,
    ) -> None:
        """Import collections from pygeoapi."""
        if not pygeoapi_configuration.is_file():
            app.error_console.print("Error: pygeoapi configuration file not found.")
            sys.exit(1)

        raw_config = await asyncio.to_thread(Path(pygeoapi_configuration).read_text)
        pygeoapi_config = await asyncio.to_thread(yaml.safe_load, raw_config)

        num_imported = 0
        async with manager.config.get_db_session_maker()() as session:
            (
                existing_admins,
                total_admins,
            ) = await postgis_operations.paginated_list_users(
                session, include_total=True, admin_filter=True
            )
            if not total_admins:
                app.error_console.print(
                    "Cannot import collections without there being at least one user "
                    "with 'admin' scope to inherit them."
                )
                sys.exit(1)
            collection_owner = existing_admins[0]
            existing_collections = (
                await collection_queries.collect_all_user_collections(session)
            )
            relevant_collections = {
                id_: res
                for id_, res in pygeoapi_config.get("resources", {}).items()
                if res.get("type") == "collection"
                and (resource is None or id_ in resource)
                and (
                    overwrite
                    or id_ not in [c.resource_identifier for c in existing_collections]
                )
            }
            for idx, (identifier, relevant_collection) in enumerate(
                relevant_collections.items()
            ):
                logger.debug(
                    f"[{idx + 1}/{len(relevant_collections)}]Processing "
                    f"collection {identifier!r}..."
                )
                try:
                    await postgis_operations.import_pygeoapi_collection(
                        session,
                        collection_owner,
                        manager.authorization_backend,
                        identifier,
                        relevant_collection,
                        manager.settings,
                        overwrite=overwrite,
                    )
                    num_imported += 1
                except PottoException as err:
                    app.error_console.print(
                        f"Could not import collection {identifier!r} - {err}"
                    )
        app.console.print(
            f"Done! Imported [{num_imported}/{len(relevant_collections)}] collections"
        )

    return app
