# docker compose file that can be used for development - do not use this in production!

name: potto

services:

  db:
    image: "postgis/postgis:17-3.5-alpine"
    environment:
      POSTGRES_DB: potto
      POSTGRES_USER: potto
      POSTGRES_PASSWORD: pottopass
    healthcheck:
      test: "pg_isready -d potto -U potto"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - target: 5432
        published: 55432
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
    image: "quay.io/keycloak/keycloak:26.5.5"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - target: 8080
        published: 58080
    volumes:
      - keycloak:/opt/keycloak/data
    healthcheck:
      test: "curl -sf http://localhost:8080/health/ready || exit 1"
      start_period: 30s
      interval: 30s
      retries: 5
      timeout: 5s
    profiles:
      - oidc

  opa:
    image: "openpolicyagent/opa:1.14.1"
    # reload policies from disk whenever they change
    command: run --server --watch --addr 0.0.0.0:8181 /policies
    ports:
      - target: 8181
        published: 58181
    volumes:
      - ./opa/policies:/policies
    healthcheck:
      test: "wget -qO- http://localhost:8181/health || exit 1"
      start_period: 5s
      interval: 15s
      retries: 3
      timeout: 3s
    profiles:
      - opa

volumes:
  db:
  keycloak:
