"""add oidc_sub to user

Revision ID: 80ca18798af8
Revises: 7c905bcd0d6e
Create Date: 2026-03-11 22:54:22.914124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "80ca18798af8"
down_revision: Union[str, Sequence[str], None] = "7c905bcd0d6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("oidc_sub", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_unique_constraint("uq_user_oidc_sub", "user", ["oidc_sub"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_oidc_sub", "user", type_="unique")
    op.drop_column("user", "oidc_sub")
    # ### end Alembic commands ###
