"""resource identifier becomes unique

Revision ID: fbbbcc48309f
Revises: 01ec4d641256
Create Date: 2026-03-05 16:20:05.351721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = 'fbbbcc48309f'
down_revision: Union[str, Sequence[str], None] = '01ec4d641256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collectionitem_resource_identifier'), table_name='collectionitem')
    op.create_index(op.f('ix_collectionitem_resource_identifier'), 'collectionitem', ['resource_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collectionitem_resource_identifier'), table_name='collectionitem')
    op.create_index(op.f('ix_collectionitem_resource_identifier'), 'collectionitem', ['resource_identifier'], unique=False)
    # ### end Alembic commands ###
