"""initial

Revision ID: bc32cdfd05a4
Revises:
Create Date: 2026-03-06 11:47:24.214786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc32cdfd05a4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "COVERAGE", "FEATURE_COLLECTION", "RECORD_COLLECTION", name="collectiontype"
    ).create(op.get_bind())
    op.create_geospatial_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "resource_identifier",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "collection_type",
            postgresql.ENUM(
                "COVERAGE",
                "FEATURE_COLLECTION",
                "RECORD_COLLECTION",
                name="collectiontype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "spatial_extent",
            Geometry(
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("temporal_extent_begin", sa.DateTime(), nullable=True),
        sa.Column("temporal_extent_end", sa.DateTime(), nullable=True),
        sa.Column(
            "additional_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("providers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_collection_spatial_extent",
        "collection",
        ["spatial_extent"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "idx_collection_title_gin",
        "collection",
        ["title"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_collection_resource_identifier"),
        "collection",
        ["resource_identifier"],
        unique=True,
    )
    op.create_table(
        "servermetadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("license", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "data_provider", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "point_of_contact", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("servermetadata")
    op.drop_index(op.f("ix_collection_resource_identifier"), table_name="collection")
    op.drop_index(
        "idx_collection_title_gin", table_name="collection", postgresql_using="gin"
    )
    op.drop_geospatial_index(
        "idx_collection_spatial_extent",
        table_name="collection",
        postgresql_using="gist",
        column_name="spatial_extent",
    )
    op.drop_geospatial_table("collection")
    sa.Enum(
        "COVERAGE", "FEATURE_COLLECTION", "RECORD_COLLECTION", name="collectiontype"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
