"""added server metadata

Revision ID: 091f0aa85633
Revises: fbbbcc48309f
Create Date: 2026-03-05 17:48:38.512039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '091f0aa85633'
down_revision: Union[str, Sequence[str], None] = 'fbbbcc48309f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pottometadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('license', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_provider', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('point_of_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pottometadata')
    # ### end Alembic commands ###
