"""added temporal extents

Revision ID: 245be7573a42
Revises: 18f4e589645d
Create Date: 2026-02-26 11:03:35.111228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = '245be7573a42'
down_revision: Union[str, Sequence[str], None] = '18f4e589645d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collectionresource', sa.Column('temporal_extent_begin', sa.DateTime(), nullable=True))
    op.add_column('collectionresource', sa.Column('temporal_extent_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collectionresource', 'temporal_extent_end')
    op.drop_column('collectionresource', 'temporal_extent_begin')
    # ### end Alembic commands ###
