"""initial

Revision ID: e0ab3140c12b
Revises: 
Create Date: 2026-02-24 21:43:29.706399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ab3140c12b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'collectionresource',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('resource_identifier', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('title', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'idx_collectionresource_name_gin', 'collectionresource', ['title'], unique=False, postgresql_using='gin'
    )
    op.create_index(
        op.f('ix_collectionresource_resource_identifier'), 'collectionresource', ['resource_identifier'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collectionresource_resource_identifier'), table_name='collectionresource')
    op.drop_index('idx_collectionresource_name_gin', table_name='collectionresource', postgresql_using='gin')
    op.drop_table('collectionresource')
    # ### end Alembic commands ###
