"""added spatial extent crs

Revision ID: f9a2a40e4df2
Revises: 18b6b1be1cb4
Create Date: 2026-04-25 23:27:33.738915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = 'f9a2a40e4df2'
down_revision: Union[str, Sequence[str], None] = '18b6b1be1cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('spatial_extent_crs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'spatial_extent_crs')
    # ### end Alembic commands ###
