"""added providers column to collection resource

Revision ID: cba562e9f41a
Revises: c2791d086465
Create Date: 2026-02-26 15:03:17.194786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba562e9f41a'
down_revision: Union[str, Sequence[str], None] = 'c2791d086465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collectionresource', sa.Column('providers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collectionresource', 'providers')
    # ### end Alembic commands ###
