"""added metadata columns

Revision ID: 77e488edc870
Revises: bc32cdfd05a4
Create Date: 2026-03-06 15:36:55.497428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77e488edc870'
down_revision: Union[str, Sequence[str], None] = 'bc32cdfd05a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servermetadata', sa.Column('keywords_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('servermetadata', sa.Column('terms_of_service', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('servermetadata', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servermetadata', 'url')
    op.drop_column('servermetadata', 'terms_of_service')
    op.drop_column('servermetadata', 'keywords_type')
    # ### end Alembic commands ###
