"""add collection is_public

Revision ID: 7c905bcd0d6e
Revises: be887326a68c
Create Date: 2026-03-11 15:40:17.848055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = '7c905bcd0d6e'
down_revision: Union[str, Sequence[str], None] = 'be887326a68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'is_public')
    # ### end Alembic commands ###
