"""cascade_delete_collections_on_user_delete

Revision ID: 8fa075facebd
Revises: 5a1f26b97088
Create Date: 2026-03-12 21:56:20.392116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "8fa075facebd"
down_revision: Union[str, Sequence[str], None] = "5a1f26b97088"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("collection_owner_id_fkey"), "collection", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "collection", "user", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("collection_owner_id_fkey", "collection", type_="foreignkey")
    op.create_foreign_key(
        "collection_owner_id_fkey", "collection", "user", ["owner_id"], ["id"]
    )
