"""added collection-crs-info

Revision ID: 18b6b1be1cb4
Revises: 9a4e4ffc09ed
Create Date: 2026-04-22 22:43:56.387614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18b6b1be1cb4'
down_revision: Union[str, Sequence[str], None] = '9a4e4ffc09ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('crs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('collection', sa.Column('storage_crs', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('collection', sa.Column('storage_crs_coordinate_epoch', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'storage_crs_coordinate_epoch')
    op.drop_column('collection', 'storage_crs')
    op.drop_column('collection', 'crs')
    # ### end Alembic commands ###
