"""add owner_id to collection

Revision ID: be887326a68c
Revises: 2f8d700ab466
Create Date: 2026-03-09 17:12:06.107984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "be887326a68c"
down_revision: Union[str, Sequence[str], None] = "2f8d700ab466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("owner_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(None, "collection", "user", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "collection", type_="foreignkey")
    op.drop_column("collection", "owner_id")
    # ### end Alembic commands ###
