"""added spatial extent to collection

Revision ID: 66509fa811f1
Revises: e0ab3140c12b
Create Date: 2026-02-25 15:11:14.081358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '66509fa811f1'
down_revision: Union[str, Sequence[str], None] = 'e0ab3140c12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('collectionresource', sa.Column('spatial_extent', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_geospatial_index('idx_collectionresource_spatial_extent', 'collectionresource', ['spatial_extent'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_collectionresource_spatial_extent', table_name='collectionresource', postgresql_using='gist', column_name='spatial_extent')
    op.drop_geospatial_column('collectionresource', 'spatial_extent')
    # ### end Alembic commands ###
