"""added shapely adapter

Revision ID: 18f4e589645d
Revises: 66509fa811f1
Create Date: 2026-02-26 11:02:24.357113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from geoalchemy2 import Geometry
from potto.db.models import ShapelyGeometryAdapter

# revision identifiers, used by Alembic.
revision: str = '18f4e589645d'
down_revision: Union[str, Sequence[str], None] = '66509fa811f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collectionresource', 'spatial_extent',
               existing_type=Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=ShapelyGeometryAdapter(dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collectionresource', 'spatial_extent',
               existing_type=ShapelyGeometryAdapter(dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
