"""added creation and modified dates to collection

Revision ID: 9a4e4ffc09ed
Revises: 8fa075facebd
Create Date: 2026-03-18 21:13:44.492657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision: str = "9a4e4ffc09ed"
down_revision: Union[str, Sequence[str], None] = "8fa075facebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("collection", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "updated_at")
    op.drop_column("collection", "created_at")
    # ### end Alembic commands ###
