"""added custom extents per collection

Revision ID: 85906f1e98e5
Revises: f9a2a40e4df2
Create Date: 2026-04-27 16:45:13.872004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85906f1e98e5'
down_revision: Union[str, Sequence[str], None] = 'f9a2a40e4df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('additional_extents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('collection', sa.Column('custom_page_size', sa.Integer(), nullable=True))
    op.add_column('collection', sa.Column('custom_page_size_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'custom_page_size_max')
    op.drop_column('collection', 'custom_page_size')
    op.drop_column('collection', 'additional_extents')
    # ### end Alembic commands ###
