class PottoException(Exception): ...


class PottoCannotSetAdminScopeException(PottoException): ...


class PottoCannotSetScopesException(PottoException): ...


class PottoCannotChangeCollectionOwnerException(PottoException): ...


class PottoCannotModifyCollectionAccessException(PottoException): ...


class PottoCannotEditCollectionException(PottoException): ...


class PottoCannotCreateCollectionException(PottoException): ...


class PottoCannotDeleteCollectionException(PottoException): ...


class PottoCannotEditServerMetadataException(PottoException): ...


class PottoCannotCreateUserException(PottoException): ...


class PottoCannotViewUserException(PottoException): ...


class PottoCannotEditUserException(PottoException): ...


class PottoCannotDeleteUserException(PottoException): ...


class PottoBadRequestException(PottoException): ...


class PottoNotFoundException(PottoException): ...


class PottoCollectionNotFoundException(PottoNotFoundException): ...


class PottoCollectionItemNotFoundException(PottoNotFoundException): ...


class CapabilityNotSupported(PottoException): ...
