name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  COLUMNS: 120

jobs:
  run_ci:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-24.04
    env:
      ARTIFACT_NAME: "python-package"
    steps:

      - name: "Grab code"
        uses: actions/checkout@v6.0.2

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Install code with dev-related dependencies"
        run: uv sync --locked --all-groups

      - name: "Run ruff formatter"
        run: uv run ruff format --check

      - name: "Run ruff linter"
        run: uv run ruff check

      - name: "Run ty"
        run: uv run ty check

#      - name: "Export OpenAPI schema document"
#        run: uv run potto export-openapi potto_openapi_ci.json
#
#      - name: "Lint OpenAPI schema with spectral"
#        uses: stoplight/spectral-action@6416fd018ae38e60136775066eb3e98172143141
#        with:
#          file_glob: potto_openapi_ci.json
#          spectral_ruleset: spectral/spectral.yaml

      - name: "Stand up compose stack for testing"
        run: |
          docker compose --file docker/compose.ci.yaml up --detach

      - name: "Run integration tests"
        env:
          POTTO__TEST_DATABASE_DSN: "postgresql+psycopg://potto:pottopass@localhost:55432/potto"
          POTTO__DEBUG: "true"
        run: uv run pytest -m integration

      - name: "Stand down compose stack"
        run: |
          docker compose --file docker/compose.ci.yaml down

      - name: "Build Python package"
        run: uv build

      - name: "Upload built package as artifact"
        id: upload_package_artifact
        uses: actions/upload-artifact@v7.0.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: dist/
          retention-days: 2
